### ISSUE TITLE
Nice

### ISSUE THREAD

**Issue by DutchPete** [Bluemoondragon07/chime-theme#1]
Nice lay-outs, and so many different themes, and, like you say, not an overwhelming amount of options. Well done.

**Comment by Bluemoondragon07** [comment]
Thanks. I'm glad you like it! I remember finding your collection of css snippets a while ago and being really impressed by the number of them. I learned a lot of css just from looking at those!

**Comment by DutchPete** [comment]
Thanks for your compliment. Now I consider Chime as a reward for your use of the snippets.
Once again, well done with Chime, I really like it, and congrats on getting it added to the community collection 👍
