### ISSUE TITLE
Table row background styling in dark mode variations of the themes

### ISSUE THREAD

**Issue by RafaelCS-Aula** [Bluemoondragon07/chime-theme#11]
Hello, I've been using this theme for a while and noticed that tables, in dark mode, don't have alternating row colouring like they do in light mode. I've checked with all the alternative colour schemes and this seems to be true for all of them. I'll include some comparison screenshots:

![Obsidian_HeE2u4btFp](https://user-images.githubusercontent.com/48124319/225761324-268bccc1-b310-4059-8974-946feab503e5.png)

![Obsidian_65eTw5pWKU](https://user-images.githubusercontent.com/48124319/225761342-58c0f76c-571d-493a-9367-f6d671289f7e.png)

Gruvbox theme:
![Obsidian_K0rcuLFWsZ](https://user-images.githubusercontent.com/48124319/225761404-16355f59-5112-4e1b-8637-c33f8393c3ff.png)
![Obsidian_wucMtSJW0k](https://user-images.githubusercontent.com/48124319/225761411-698bbab6-e42c-43df-a0d0-2178c3720977.png)

It seems like a small oversight but it would make tables easier to parse trough in dark mode if they had the row BGs alternate like they have in light mode.

**Comment by Bluemoondragon07** [comment]
Thanks for pointing this out! This has been fixed in the latest update.
