### ISSUE TITLE
[FR] Add support to customise inline code

### ISSUE THREAD

**Issue by zanodor** [Bluemoondragon07/chime-theme#12]
I was looking for a lightweight theme with a non-creamy/blurry/hazy surface and I have found it.  

I often quote authors who provide lexical items (vocabulary items) which I highlight using `backticks`. Especially in these blockquotes the items are difficult to tell apart from the main block of text.  

Could you add customisability to inline code as well please? Preferably colour and the option to remove the background.  

Keep up the good work,

Cheers

**Comment by Bluemoondragon07** [comment]
Thanks for the suggestion! Sorry about the bad visibility with the inline code--I didn't pay much attention to it when I first made the theme 😅. I'll definitely add some customization options for inline code in the next update.

**Comment by Bluemoondragon07** [comment]
I finally found the time to update the theme and added some options for codeblocks. ⭐ Enjoy!
