### ISSUE TITLE
关于标签栏上的标题辨识度

### ISSUE THREAD

**Issue by zanghuaren** [Bluemoondragon07/chime-theme#13]
标签栏上的字体像是被添加了透明度导致标题看得不太清，在插件StyleSetting中也没有相关调整的选项。能否出一个设置，可以进行调节。
<img width="692" alt="Snipaste_2023-04-12_22-16-29" src="https://user-images.githubusercontent.com/102011265/231486907-d1f18b62-9602-416c-9ecc-ff62aa0ff644.png">

**Comment by Bluemoondragon07** [comment]
我正在使用谷歌翻译，如果这听起来不正确，我深表歉意。

这真是个好主意。 默认情况下，选项卡使用强调色，因此我将添加一个设置以在下一次更新中更改它！

**Comment by zanghuaren** [comment]
好的，非常感谢你！我很喜欢这个主题！

**Comment by zanghuaren** [comment]
Another idea I have is to add an option that cancels the surrounding space in full screen mode. I know very little CSS so I don't know how to do this.
Thanks again.
<img width="1280" alt="Snipaste_2023-04-14_15-50-54" src="https://user-images.githubusercontent.com/102011265/231981396-08dc6213-3b26-4a82-8bfa-891c7b9e9571.png">

**Comment by Bluemoondragon07** [comment]
I just updated the theme! Now you can go to `Style Settings > Tabs` and choose a different color for active tabs.

Also, to get rid of the extra space in Full Screen mode, you can now go to `Style Settings > Editor` and change the Readable Line Length to make the text wider. Turning on classic layout in `Style Settings > Layout` will also eliminate some of that extra space.

⭐ Enjoy.

---

我刚刚更新了主题！ 现在您可以转到“样式设置”>“选项卡”并为活动选项卡选择不同的颜色。

此外，要消除全屏模式下的额外空间，您现在可以转到“样式设置”>“编辑器”并更改“可读行长”以使文本变宽。 在 Style Settings > Layout 中打开经典布局也将消除一些额外的空间。

⭐ 享受吧。

**Comment by zanghuaren** [comment]
Oh, great! how beautiful it is.
