### ISSUE TITLE
How can I get cards view like this?

### ISSUE THREAD

**Issue by PencilMing** [Bluemoondragon07/chime-theme#20]
![image](https://github.com/Bluemoondragon07/chime-theme/assets/82462283/7faabbb7-7786-4804-900e-e8ffd6eb0dca)
hi ,how can I get this cards view in chime? would you like give a link to Pages Gallery plug-in.？

**Comment by Bluemoondragon07** [comment]
Sorry for the late reply; this is the link!  - https://github.com/tokenshift/obsidian-page-gallery

The plugin has updated a lot since Chime was released though, so the styling may be different; I have not updated Chime as often as Page Gallery updates.
