### ISSUE TITLE
PDF printing  black line in right margin

### ISSUE THREAD

**Issue by samaellain** [Bluemoondragon07/chime-theme#4]
![2023-02-11 (1)](https://user-images.githubusercontent.com/56184334/218270055-fcd636a1-b97d-4bcd-a6bf-5d2014d0bdc0.png)
Is this intended?

**Comment by samaellain** [comment]
Obsidian v1.1.9
installer version v1.1.9
Chime theme v1.1.5

**Comment by samaellain** [comment]
This snipet resolve the problem
```css
body {
    border-right-style: none
}
```

in the line 174 from theme.

**Comment by Bluemoondragon07** [comment]
Thank you for bringing this to my attention, @samaellain. This issue has been fixed in the latest update!
